Feature/better switch command (#7)
* Adding a better switch command and a way to retrieve the account/env/cluster via the context command

* Adding holdweb and fixing issues where there are multiple package.json files in subdirectories

diff --git a/plugins/av-clusters/bin/inventory b/plugins/av-clusters/bin/inventory
--- a/plugins/av-clusters/bin/inventory
+++ b/plugins/av-clusters/bin/inventory
@@ -14,14 +14,14 @@ avCheckHelpFlags "$1" "builtin" "Operate on inventory" "\n \
 avAppendSystemPath
 
 #### Put system commands here
-cluster=$(getpv cluster)
-if [[ -z $cluster ]]; then
-	echo "Unable to find cluster..."
+
+# Get context
+context=`context`
+if [[ $? -ne 0 ]]; then
+	echo "Unable to determine context, please use 'switch' command to set."
 	exit 1
 fi
-folder=`getpv clusterdir`
-environment=`getpv environment`
 
-/bin/cat $AV_ROOT/../$folder/$cluster/$environment/inventory/inventory.hosts
+/bin/cat $context/inventory/inventory.hosts
 
 #### End commands
diff --git a/plugins/av-clusters/bin/tf b/plugins/av-clusters/bin/tf
--- a/plugins/av-clusters/bin/tf
+++ b/plugins/av-clusters/bin/tf
@@ -12,16 +12,15 @@ avCheckHelpFlags "$1" "builtin" "template script" "\n \
 
 
 #### Put system commands here
-folder=`getpv clusterdir`
-cluster=$(getpv cluster)
-if [[ -z $cluster ]]; then
-	echo "Unable to find cluster..."
+# Get context
+context=`context`
+if [[ $? -ne 0 ]]; then
+	echo "Unable to determine context, please use 'switch' command to set."
 	exit 1
 fi
-environment=`getpv environment`
 
 # Import system path
 avRestoreSystemPath
-cd $AV_ROOT/../$folder/$cluster/$environment/terraform && terraform $*
+cd $context/terraform && terraform $*
 
 #### End commands
