feat(docker): use tagstyles to select they path
`holdtag` is now `tagstyle` with a menu-select.

diff --git a/plugins/av-docker/bin/push b/plugins/av-docker/bin/push
--- a/plugins/av-docker/bin/push
+++ b/plugins/av-docker/bin/push
@@ -35,21 +35,29 @@ else
 	container_domain=$container
 fi
 
-# Check for holdtag setting
-tag_style=$(getpv holdtag)
+# Check for tagstyle setting
+tag_style=$(getpv tagstyle)
 
 tag_value=$1
 if [ $# -lt 1 ]; then
 	tag_value=$(codehash)
 fi
 
-# Apply tag style based on holdtag setting
-if [[ "$tag_style" == "name-override" ]]; then
+# Apply tag style based on tagstyle setting
+if [[ -z "$tag_style" ]]; then
+	echo -e "${txtred}No tag style set. Run 'tagstyle' to choose a format${txtrst}"
+	exit 1
+fi
+
+if [[ "$tag_style" == "sans-domain" ]]; then
 	container_push=$repo/$container:$tag_value
 elif [[ "$tag_style" == "one-repo" ]]; then
 	container_push=$repo/$container_domain:$container-$tag_value
-else
+elif [[ "$tag_style" == "with-domain" ]]; then
 	container_push=$repo/$container_domain/$container:$tag_value
+else
+	echo -e "${txtred}Invalid tag style '$tag_style'. Run 'tagstyle' to choose a valid format.${txtrst}"
+	exit 1
 fi
 
 # Import system path
diff --git a/plugins/av-docker/bin/tag b/plugins/av-docker/bin/tag
--- a/plugins/av-docker/bin/tag
+++ b/plugins/av-docker/bin/tag
@@ -7,9 +7,12 @@ source $AV_CONFIG_DIR/default_imports
 avCheckHelpFlags "$1" "docker" "Tag current container on a repository" "\
 Usage: 
 
-    tag [version]
+    tag [--verbose] [version]
 
-        Resulting image path will change based on the holdtag setting.
+        --verbose  Show the full image path being tagged
+        version   Version to tag with (defaults to codehash)
+
+        Resulting image path will change based on the tagstyle setting.
 "
 
 # Import system path
@@ -21,6 +24,13 @@ avAppendSystemPath
 provider=$(container_provider)
 if [ -z "$provider" ]; then
     provider="docker"
+fi
+
+# Check for verbose flag
+verbose=false
+if [[ "$1" == "--verbose" ]]; then
+    verbose=true
+    shift
 fi
 
 tag_value=$1
@@ -54,16 +64,30 @@ else
 	container_domain=$container
 fi
 
-# Check for holdtag setting
-tag_style=$(getpv holdtag)
+# Check for tagstyle setting
+tag_style=$(getpv tagstyle)
 
-# Apply tag style based on holdtag setting
-if [[ "$tag_style" == "name-override" ]]; then
+# Apply tag style based on tagstyle setting
+if [[ -z "$tag_style" ]]; then
+	echo -e "${txtred}No tag style set. Run 'tagstyle' to choose a format:${txtrst}"
+	exit 1
+fi
+
+if [[ "$tag_style" == "sans-domain" ]]; then
 	container_push=$repo/$container:$tag_value
 elif [[ "$tag_style" == "one-repo" ]]; then
 	container_push=$repo/$container_domain:$container-$tag_value
-else
+elif [[ "$tag_style" == "with-domain" ]]; then
 	container_push=$repo/$container_domain/$container:$tag_value
+else
+	echo -e "${txtred}Invalid tag style '$tag_style'. Run 'tagstyle' to choose a valid format.${txtrst}"
+	exit 1
+fi
+
+# Show full path if verbose mode is enabled
+if [[ "$verbose" == "true" ]]; then
+    echo -e "Tagging image:"
+    echo -e "    ${bldwht}${container_push}${txtrst}"
 fi
 
 avCheckVerbose "$provider tag $domain/$container ${container_push}"
