Adding a better switch command and a way to retrieve the account/env/cluster via the context command

diff --git a/plugins/av-aws/bin/sam b/plugins/av-aws/bin/sam
--- a/plugins/av-aws/bin/sam
+++ b/plugins/av-aws/bin/sam
@@ -13,17 +13,15 @@ avCheckHelpFlags "$1" "av-aws" "Run serverless application model (SAM) on select
 
 #### Put system commands here
 
-cluster=$(getpv cluster)
-if [[ -z $cluster ]]; then
-	echo "Unable to find cluster..."
+# Get context
+context=`context`
+if [[ $? -ne 0 ]]; then
+	echo "Unable to determine context, please use 'switch' command to set."
 	exit 1
 fi
-folder=`getpv clusterdir`
-environment=`getpv environment`
 
 # Import system path
 avRestoreSystemPath
-echo "cd $AV_ROOT/../$folder/$cluster/$environment/sam && sam $*"
-cd $AV_ROOT/../$folder/$cluster/$environment/sam && sam $*
+cd $context/sam && sam $*
 
 #### End commands
diff --git a/plugins/av-clusters/bin/ansible b/plugins/av-clusters/bin/ansible
--- a/plugins/av-clusters/bin/ansible
+++ b/plugins/av-clusters/bin/ansible
@@ -14,12 +14,14 @@ avCheckHelpFlags "$1" "builtin" "Run ansible on selected cluster" "\n \
 avAppendSystemPath
 
 #### Put system commands here
-folder=$(getpv cluster)
-if [[ -z $folder ]]; then
-	echo "Unable to find cluster..."
+
+# Get context
+context=`context`
+if [[ $? -ne 0 ]]; then
+	echo "Unable to determine context, please use 'switch' command to set."
 	exit 1
 fi
 
-cd $AV_ROOT/../`getpv clusterdir`/$folder/ansible && ansible-playbook -i $AV_ROOT/../`getpv clusterdir`/$folder/inventory/inventory.hosts $1.yaml
+cd $context/ansible && ansible-playbook -i $context/inventory/inventory.hosts $1.yaml
 
 #### End commands
